apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: web
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100
  selector:
    app: nginx
