apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: web
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
      - name: wordpress-vol
        persistentVolumeClaim:
          claimName: wp-pvc
      containers:
      - name: wordpress
        image: wordpress
        env:
          - name: WORDPRESS_DB_USER
            value: "wordpress"
          - name: WORDPRESS_DB_NAME
            value: "wordpress"
          - name: WORDPRESS_DB_PASSWORD
            value: "password"
          - name: WORDPRESS_DB_HOST
            value: "212.162.147.185:30200"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-vol
          mountPath: /var/www/html
