apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: web
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30200
  selector:
    app: mariadb
